"""empty message

Revision ID: b1720dfbd2e3
Revises: 874ce8c272cb
Create Date: 2024-08-07 10:53:22.605612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1720dfbd2e3'
down_revision = '874ce8c272cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos_peoples', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_favorito',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('favoritos_planets', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_favorito',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('favoritos_vehicles', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_favorito',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('favoritos_vehicles', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_favorito',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('favoritos_planets', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_favorito',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('favoritos_peoples', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_favorito',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
