"""empty message

Revision ID: d06c3fe204d1
Revises: b1720dfbd2e3
Create Date: 2024-08-07 11:36:21.102271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06c3fe204d1'
down_revision = 'b1720dfbd2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.String(length=250), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.Column('surface', sa.String(length=250), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planet')
    with op.batch_alter_table('favoritos_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favoritos_planets_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['homeworld'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('people_homeworld_fkey', 'planet', ['homeworld'], ['id'])

    with op.batch_alter_table('favoritos_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_planets_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.drop_column('planets_id')

    op.create_table('planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('population', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('rotation_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orbital_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gravity', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('surface', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planet_pkey')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###
